make

diff --git a/.github/workflows/sphinx.yml b/.github/workflows/sphinx.yml
--- a/.github/workflows/sphinx.yml
+++ b/.github/workflows/sphinx.yml
@@ -38,44 +38,44 @@ jobs:
       run: |
           cd docs
           make html
-    # upload
-    # - name: Upload artifacts
-    #   uses: actions/upload-artifact@v3
-    #   with:
-    #     name: html-docs
-    #     path: docs/_build/html/
-    # # Deploy
-    # - name: Deploy
-    #   uses: peaceiris/actions-gh-pages@v3
-    #   with:
-    #     github_token: ${{ secrets.GITHUB_TOKEN }}
-    #     publish_dir: docs/_build/html
-    # Publish built docs to gh-pages branch.
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/malsabbagh-mhp/pages-repo.git --branch gh-pages --single-branch gh-pages
-        ls gh-pages/
-        echo "HALLO"
-        ls docs/_build/html/
-        echo "HALLO"
-        cp -r docs/_build/html/* gh-pages/
-        ls gh-pages/
-        echo "HALLO"
-        ls docs/_build/html/
-        echo "HALLO"
-        cd gh-pages
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
+    upload
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v3
       with:
-        branch: gh-pages
-        directory: gh-pages
+        name: html-docs
+        path: docs/_build/html/
+    # Deploy
+    - name: Deploy
+      uses: peaceiris/actions-gh-pages@v3
+      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
+        publish_dir: docs/_build/html
+    Publish built docs to gh-pages branch.
+    # ===============================
+    # - name: Commit documentation changes
+    #   run: |
+    #     git clone https://github.com/malsabbagh-mhp/pages-repo.git --branch gh-pages --single-branch gh-pages
+    #     ls gh-pages/
+    #     echo "HALLO"
+    #     ls docs/_build/html/
+    #     echo "HALLO"
+    #     cp -r docs/_build/html/* gh-pages/
+    #     ls gh-pages/
+    #     echo "HALLO"
+    #     ls docs/_build/html/
+    #     echo "HALLO"
+    #     cd gh-pages
+    #     touch .nojekyll
+    #     git config --local user.email "action@github.com"
+    #     git config --local user.name "GitHub Action"
+    #     git add .
+    #     git commit -m "Update documentation" -a || true
+    #     # The above command will fail if no changes were present, so we ignore
+    #     # that.
+    # - name: Push changes
+    #   uses: ad-m/github-push-action@master
+    #   with:
+    #     branch: gh-pages
+    #     directory: gh-pages
+    #     github_token: ${{ secrets.GITHUB_TOKEN }}
     # # ===============================
